DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS_GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP SEQUENCE IF EXISTS AUTHORS_ID_SEQ;
DROP SEQUENCE IF EXISTS GENRES_ID_SEQ;
DROP SEQUENCE IF EXISTS BOOKS_ID_SEQ;
DROP SEQUENCE IF EXISTS COMMENTS_ID_SEQ;

CREATE TABLE AUTHORS
(
    ID          BIGSERIAL PRIMARY KEY,
    FIRST_NAME  VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME   VARCHAR(255) NOT NULL
);

CREATE TABLE GENRES
(
    ID   BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS
(
    ID            BIGSERIAL PRIMARY KEY,
    AUTHOR_ID     BIGINT NOT NULL,
    TITLE         VARCHAR(255),
    SHORT_CONTENT VARCHAR(1024),
    CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE RESTRICT
);
CREATE TABLE COMMENTS
(
    ID           BIGSERIAL PRIMARY KEY,
    BOOK_ID      BIGINT    NOT NULL,
    USER_NAME    VARCHAR(255),
    COMMENT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONTENT      VARCHAR(5000),
    CONSTRAINT FK_BOOK_COMMENT FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID)
);

CREATE TABLE BOOKS_GENRES
(
    BOOK_ID  BIGINT,
    GENRE_ID BIGINT,
    PRIMARY KEY (BOOK_ID, GENRE_ID),
    CONSTRAINT FK_BOOK_GENRE FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID),
    CONSTRAINT FK_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE RESTRICT
);


