spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarydb
mongock:
  runner-type: InitializingBean
  migration-scan-package:
    - ru.otus.hw11.changelogs
logging:
  level:
    ROOT: info
server:
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always

