DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS_GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME  VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME   VARCHAR(255) NOT NULL
);

CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_ID     BIGINT NOT NULL,
    TITLE         VARCHAR(255),
    SHORT_CONTENT VARCHAR(1024),
    AGE_RESTRICT  BOOLEAN,
    CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE RESTRICT
);
CREATE TABLE COMMENTS
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOOK_ID      BIGINT    NOT NULL,
    USER_NAME    VARCHAR(255),
    COMMENT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONTENT      VARCHAR(5000),
    CONSTRAINT FK_BOOK_COMMENT FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID)
);

CREATE TABLE BOOKS_GENRES
(
    BOOK_ID  BIGINT,
    GENRE_ID BIGINT,
    PRIMARY KEY (BOOK_ID, GENRE_ID),
    CONSTRAINT FK_BOOK_GENRE FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID),
    CONSTRAINT FK_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE RESTRICT
);
CREATE TABLE ROLES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

CREATE TABLE USERS
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(255),
    PASSWORD VARCHAR(255),
    ENABLED  BOOLEAN,
    LOCKED   BOOLEAN,
    EXPIRED  BOOLEAN
);

CREATE TABLE USERS_ROLES
(
    USER_ID BIGINT,
    ROLE_ID BIGINT,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROLE_USER FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE RESTRICT
);



CREATE TABLE IF NOT EXISTS ACL_SID
(
    ID        BIGINT(20)   NOT NULL AUTO_INCREMENT,
    PRINCIPAL TINYINT(1)   NOT NULL,
    SID       VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UNIQUE_UK_1 (SID,PRINCIPAL)
);
CREATE TABLE IF NOT EXISTS ACL_CLASS
(
    ID    BIGINT(20)   NOT NULL AUTO_INCREMENT,
    CLASS VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UNIQUE_UK_2 (CLASS)
);


CREATE TABLE IF NOT EXISTS ACL_OBJECT_IDENTITY
(
    ID                 BIGINT(20) NOT NULL AUTO_INCREMENT,
    OBJECT_ID_CLASS    BIGINT(20) NOT NULL,
    OBJECT_ID_IDENTITY BIGINT(20) NOT NULL,
    PARENT_OBJECT      BIGINT(20) DEFAULT NULL,
    OWNER_SID          BIGINT(20) DEFAULT NULL,
    ENTRIES_INHERITING TINYINT(1) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UNIQUE_UK_3 (OBJECT_ID_CLASS,OBJECT_ID_IDENTITY),
    CONSTRAINT FK_ACL_OBJECT_PARENT FOREIGN KEY (PARENT_OBJECT) REFERENCES ACL_OBJECT_IDENTITY (ID),
    CONSTRAINT FK_ACL_OBJECT_CLASS FOREIGN KEY (OBJECT_ID_CLASS) REFERENCES ACL_CLASS (ID),
    CONSTRAINT FK_ACL_OBJECT_IDENTITY FOREIGN KEY (OWNER_SID) REFERENCES ACL_SID (ID)
);

CREATE TABLE IF NOT EXISTS ACL_ENTRY
(
    ID                  BIGINT(20) NOT NULL AUTO_INCREMENT,
    ACL_OBJECT_IDENTITY BIGINT(20) NOT NULL,
    ACE_ORDER           INT(11)    NOT NULL,
    SID                 BIGINT(20) NOT NULL,
    MASK                INT(11)    NOT NULL,
    GRANTING            TINYINT(1) NOT NULL,
    AUDIT_SUCCESS       TINYINT(1) NOT NULL,
    AUDIT_FAILURE       TINYINT(1) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UNIQUE_UK_4 (ACL_OBJECT_IDENTITY,ACE_ORDER),
    CONSTRAINT FK_ACL_ENTRY_OBJECT FOREIGN KEY (ACL_OBJECT_IDENTITY) REFERENCES ACL_OBJECT_IDENTITY (ID),
    CONSTRAINT FK_ACL_ENTRY_SID FOREIGN KEY (SID) REFERENCES ACL_SID (ID)
);



