DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS BOOKS_GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME  VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME   VARCHAR(255) NOT NULL
);

CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_ID     BIGINT NOT NULL,
    TITLE         VARCHAR(255),
    SHORT_CONTENT VARCHAR(1024),
    CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE RESTRICT
);
CREATE TABLE COMMENTS
(
    ID           BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOOK_ID      BIGINT    NOT NULL,
    USER_NAME    VARCHAR(255),
    COMMENT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONTENT      VARCHAR(5000),
    CONSTRAINT FK_BOOK_COMMENT FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID)
);

CREATE TABLE BOOKS_GENRES
(
    BOOK_ID  BIGINT,
    GENRE_ID BIGINT,
    PRIMARY KEY (BOOK_ID, GENRE_ID),
    CONSTRAINT FK_BOOK_GENRE FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID),
    CONSTRAINT FK_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE RESTRICT
);
CREATE TABLE ROLES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

CREATE TABLE USERS
(
    ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME     VARCHAR(255),
    PASSWORD VARCHAR(255),
    ENABLED  BOOLEAN,
    LOCKED   BOOLEAN,
    EXPIRED  BOOLEAN
);

CREATE TABLE USERS_ROLES
(
    USER_ID BIGINT,
    ROLE_ID BIGINT,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROLE_USER FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE RESTRICT
);
