DROP TABLE IF EXISTS BOOKS_GENRES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
CREATE TABLE AUTHORS
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME  VARCHAR(255) NOT NULL,
    MIDDLE_NAME VARCHAR(255),
    LAST_NAME   VARCHAR(255) NOT NULL
);

CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BOOKS
(
    ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_ID     BIGINT NOT NULL,
    TITLE         VARCHAR(255),
    SHORT_CONTENT VARCHAR(1024),
    CONSTRAINT FK_BOOK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE BOOKS_GENRES
(
    BOOK_ID  BIGINT,
    GENRE_ID BIGINT,
    PRIMARY KEY (BOOK_ID, GENRE_ID),
    CONSTRAINT FK_BOOK_GENRE FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_GENRE FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID) ON DELETE RESTRICT ON UPDATE CASCADE
);


